### ISSUE TITLE
运行wvp程序后，媒体服务器未出现注册消息和接收流操作。

### ISSUE THREAD

**Issue by perryDavid** [swwheihei/wvp-GB28181#14]
1.配置Media地址和端口
2.完成摄像头SIP服务器配置
3.调用play接口， ZLMediaKit未出现注册消息以及流消息。
请各位大佬，帮忙看看，谢谢。

**Comment by FlickerMi** [comment]
内网还是公网服务器？
请贴出wvp项目的配置文件。

**Comment by swwheihei** [comment]
长时间未反馈，issues关闭

**Comment by jiangyang118** [comment]
我这边也出现，公网服务器
