### ISSUE TITLE
启动发生循环依赖

### ISSUE THREAD

**Issue by tsinemperor** [swwheihei/wvp-GB28181#19]
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'registerLogicHandler': Unsatisfied dependency expressed through field 'cmder'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'SIPCommander': Unsatisfied dependency expressed through field 'headerProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'SIPRequestHeaderProvider': Unsatisfied dependency expressed through field 'sipFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sipLayer': Unsatisfied dependency expressed through field 'processorFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'SIPProcessorFactory': Unsatisfied dependency expressed through field 'tcpSipProvider'; nested exception is 

_**org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'initSipServer': Requested bean is currently in creation: Is there an unresolvable circular reference?**_

**Comment by swwheihei** [comment]
3Q，问题已解决
