### ISSUE TITLE
多厂家设备兼容问题：按照wiki整了一套环境，仅大华的一台设备能用rtmp播放

### ISSUE THREAD

**Issue by bulexx** [swwheihei/wvp-GB28181#20]
仅大华的一台设备能用rtmp播放（vlc播放器）；华为的两台和兴唐的一台可以发现注册设备，调用了play接口，devices接口都有返回设备列表；但是没有推流。这些有哪些解决办法。

**Comment by swwheihei** [comment]
目前兼容主流的海康、大华，市场占有率很低的华为、兴唐等未做适配（主要是我没有这个设备，没法调试），需要抓包排查问题

**Comment by bulexx** [comment]
这几天研究了一下，hw的推流要在发送ACK的时候不用via的地址和port就可以，via里的信息是错的。还有一些问题是流媒体服务器的问题。
