### ISSUE TITLE
wiki问题

### ISSUE THREAD

**Issue by hrdzkj** [swwheihei/wvp-GB28181#6]
wiki里面的视频请求流程，的图片看不见，无法了解视频请求的流程。能不能处理一下呢。
谢谢！

**Comment by swwheihei** [comment]
可以的，稍后处理下

**Comment by SNGxx** [comment]
@swwheihei 图片里的流程好像和GB28181文档里“实时视频点播”里的流程不同？
国标里的流程好长。

**Comment by SNGxx** [comment]
> wiki里面的视频请求流程，的图片看不见，无法了解视频请求的流程。能不能处理一下呢。
> 谢谢！

国标java开发老哥求交流。。

**Comment by swwheihei** [comment]
国标里定义的UI、SIP服务、流媒体、摄像头互相通信都是SIP信令，并不符合实际场景，实际上UI、SIP服务、流媒体之间通信用http即可，只需要SIP服务与摄像头通信，故简化了流程

**Comment by SNGxx** [comment]
> 国标里定义的UI、SIP服务、流媒体、摄像头互相通信都是SIP信令，并不符合实际场景，实际上UI、SIP服务、流媒体之间通信用http即可，只需要SIP服务与摄像头通信，故简化了流程

明白了，感谢回复。

**Comment by kevin-onepiece** [comment]
可以分享一下视频请求流程的图片吗，先谢谢了
